server:
  port: 8002
  servlet:
    context-path: /im

#log4j
logging:
  pattern:
    console: "%d - %msg%n"
  level:
    org:
      springframework:
        web: info
    root: info

spring:
  redis:
    host: your ip
    password: your password
    timeout: 2000